const String USERS_COLLECTION = 'USERS';
const String GROUPS_COLLECTION = 'GROUPS';
const String MESSAGES_COLLECTION = 'MESSAGES';
const String NOTES_COLLECTION = 'NOTES';
const String EVENTS_COLLECTION = 'EVENTS';
